# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'benhvien-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'MBProgressHUD', '~> 1.0'
  pod 'PureLayout', '~> 3.0'
  pod 'IQKeyboardManager'
  pod 'IQDropDownTextField', '~> 1.1'
  pod 'KASlideShow', '~> 3.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end
